version: "3.9"

services:

  api:
    build: .
    container_name: emotion-risk-engine

    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on:
      - postgres

    restart: unless-stopped

  postgres:
    image: postgres:16

    container_name: emotion-risk-db

    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: emotion_risk_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: